import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/index.tsx"),
    route("services", "routes/services.tsx"),
    route("work", "routes/portfolio.tsx"),
    route("process", "routes/process.tsx"),
    route("contact", "routes/contact.tsx"),
    route("start-a-project", "routes/start-a-project.tsx"),
    route("login", "routes/auth/login.tsx"),
    route("admin", "routes/admin/index.tsx"),
    route("admin/leads", "routes/admin/leads.tsx"),
    route("admin/pipeline", "routes/admin/pipeline.tsx"),
    route("admin/proposals", "routes/admin/proposals.tsx"),
    route("admin/follow-ups", "routes/admin/follow-ups.tsx"),
    route("admin/projects", "routes/admin/projects.tsx"),
    route("admin/projects/new", "routes/admin/projects.new.tsx"),
    route("admin/projects/:projectId", "routes/admin/projects.$projectId.tsx"),
    route("admin/documents", "routes/admin/documents.tsx"),
    route("admin/documents/new", "routes/admin/documents.new.tsx"),
    route("admin/documents/:documentId", "routes/admin/documents.$documentId.tsx"),
    route("admin/documents/:documentId/edit", "routes/admin/documents.$documentId.edit.tsx"),
    route("admin/tasks", "routes/admin/tasks.tsx"),
    route("admin/clients", "routes/admin/clients.tsx"),
    route("admin/files", "routes/admin/files.tsx"),
    route("admin/messages", "routes/admin/messages.tsx"),
    route("admin/websites", "routes/admin/websites.tsx"),
    route("admin/reports", "routes/admin/reports.tsx"),
    route("admin/analyzer", "routes/admin/analyzer.tsx"),
    route("admin/seo", "routes/admin/seo.tsx"),
    route("admin/uptime", "routes/admin/uptime.tsx"),
    route("admin/finance", "routes/admin/finance.tsx"),
    route("admin/invoices", "routes/admin/invoices.tsx"),
    route("admin/payments", "routes/admin/payments.tsx"),
    route("admin/expenses", "routes/admin/expenses.tsx"),
    route("admin/bookkeeping", "routes/admin/bookkeeping.tsx"),
    route("admin/ai-tools", "routes/admin/ai-tools.tsx"),
    route("admin/proposal-generator", "routes/admin/proposal-generator.tsx"),
    route("admin/copywriter", "routes/admin/copywriter.tsx"),
    route("admin/lead-finder", "routes/admin/lead-finder.tsx"),
    route("admin/calendar", "routes/admin/calendar.tsx"),
    route("admin/email", "routes/admin/email.tsx"),
    route("admin/settings", "routes/admin/settings.tsx"),
    route("admin/login", "routes/auth/admin-login.tsx"),
    route("portal/invite/:token", "routes/portal/invite.tsx"),
    route("portal/dashboard", "routes/portal/dashboard.tsx"),
    route("portal/documents", "routes/portal/documents.tsx"),
    route("portal/documents/:documentId", "routes/portal/documents.$documentId.tsx"),
    route("sign/mobile/:token", "routes/sign.mobile.$token.tsx"),
    route("portal/invoices", "routes/portal/invoices.tsx"),
    route("portal/messages", "routes/portal/messages.tsx"),
    route("portal/files", "routes/portal/files.tsx"),
    route("portal/support", "routes/portal/support.tsx"),
    route("portal", "routes/portal/index.tsx"),
] satisfies RouteConfig;
